[package]
name = "ubot"
version = "0.1.0"
authors = ["Andrey Korotaev <andrey.korotaev@norbit.com>"]
edition = "2018"

[dependencies]
tokio-amqp = "1.0"
lapin = "1.7"
tokio = {version="1.6", features = ["full"]}
irc = "0.15"
anyhow = "1.0"
futures = "0.3"
url = "2.2"
rand = "0.8"
