[package]
name = "ubot-plugin-janitor"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
tokio-amqp = "1.0"
lapin = "1.7"
tokio = {version="1.6", features = ["full"]}
rand = "0.8"
futures = "0.3"
