[package]
name = "hedgewars-network-protocol"
version = "0.1.0"
authors = ["Andrey Korotaev <a.korotaev@hedgewars.org>"]
edition = "2021"

[dependencies]
nom = "7.1"
serde_derive = "1.0"
serde = "1.0"

[dev-dependencies]
proptest = "1.0"