[package]
name = "ubot-mingpt-plugin"
version = "0.1.0"
authors = ["Andrey Korotaev <a.korotaev@hedgewars.org>"]
edition = "2018"

[dependencies]
tch = "0.4"
anyhow = "1.0"
tokio-amqp = "1.0"
lapin = "1.7"
tokio = {version="1.6", features = ["full"]}
rand = "0.8"
futures = "0.3"

